import type { Metadata } from "next";
import { Demo } from "@/components/Demo";

const TITLE = "Try it · Refugio";
const DESCRIPTION =
  "A no-install, web version of Refugio's core mechanic — add guardians, watch the fire grow, and feed it before it burns out.";

export const metadata: Metadata = {
  title: TITLE,
  description: DESCRIPTION,
  alternates: { canonical: "/demo" },
  // Without these, shared links would pair this route's dedicated OG image (generated by
  // opengraph-image.tsx, auto-detected by Next) with the ROOT layout's generic Wall title —
  // Next only inherits unspecified metadata keys wholesale, it doesn't merge per-field.
  openGraph: { title: TITLE, description: DESCRIPTION, type: "website" },
  twitter: { card: "summary_large_image", title: TITLE, description: DESCRIPTION },
};

export default function DemoPage() {
  return <Demo />;
}
